[package]
name = "scamoku"
version = "0.1.0"
authors = ["Scallop Ye <yescallop@gmail.com>"]
edition = "2021"

[dependencies]
thiserror = "1.0"
tokio = { version = "1.18.2", features = ["rt", "sync"] }
# once_cell = "1.11.0"
